# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FBDateFormatExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FBDateFormat', :path => "../FBDateFormat"

  # Pods for FBDateFormatExample

  target 'FBDateFormatExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FBDateFormatExampleUITests' do
    # Pods for testing
  end

end
