# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FBDateFormat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FBDateFormat

  target 'FBDateFormatTests' do
    # Pods for testing
  end

end
